version: '2'

services:
  server:
    build: ./
    container_name: video_webpage
    image: video_webpage
    ports:
      - "8080:3000"
    restart: always
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - intra
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ../database/:/data/db
    networks:
      - intra

networks:
  intra:
    driver: bridge
